/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fatec.museu.view;

import com.fatec.museu.controllers.ControleGerenciarAcervo;
import javax.swing.table.DefaultTableModel;
import com.fatec.museu.model.Obra;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;


/**
 *
 * @author Panda
 */
public class FormGerenciaObra extends javax.swing.JInternalFrame {
    static private FormGerenciaObra instanciaObra;
    private ControleGerenciarAcervo controle = new ControleGerenciarAcervo();
    /**
     * Creates new form FormGerenciaObra
     */
    public FormGerenciaObra() {
        initComponents();
    }

    public static FormGerenciaObra getInstance() {
        if(instanciaObra == null) {
            instanciaObra = new FormGerenciaObra();
        }
        return instanciaObra;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngTipoObra = new javax.swing.ButtonGroup();
        btnCadastrar = new com.fatec.museu.util.GradientButton();
        btnVoltar = new com.fatec.museu.util.GradientButton();
        txtTitulo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbTipoObra = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDadosBiograficos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDoadorObra = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();
        btnProcurarImagem = new com.fatec.museu.util.GradientButton();
        jLabel9 = new javax.swing.JLabel();
        btnExcluir = new com.fatec.museu.util.GradientButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_dados = new javax.swing.JTable();
        btnAlterar = new com.fatec.museu.util.GradientButton();
        txtDataObra = new javax.swing.JFormattedTextField();
        rdbObraFisica = new javax.swing.JRadioButton();
        rdbObraVirtual = new javax.swing.JRadioButton();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 350, 90, 40));

        btnVoltar.setText("Voltar");
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 700, 100, 40));

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 210, 30));

        jLabel1.setText("Título");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, 30));

        jLabel2.setText("Data da Obra");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 70, 30));

        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 200, 30));

        jLabel3.setText("Categoria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, 30));

        cmbTipoObra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbTipoObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 170, 30));

        jLabel4.setText("Tipo de Obra");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 70, -1));

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });
        getContentPane().add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 170, 30));

        jLabel5.setText("Autor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, 30));

        txtDadosBiograficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDadosBiograficosActionPerformed(evt);
            }
        });
        getContentPane().add(txtDadosBiograficos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 210, 100));

        jLabel6.setText("Dados Biográficos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 30));

        txtDoadorObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoadorObraActionPerformed(evt);
            }
        });
        getContentPane().add(txtDoadorObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 200, 30));

        jLabel7.setText("Doador da Obra");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 80, 30));

        lblImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 350, 240));

        btnProcurarImagem.setText("Procurar Imagem");
        btnProcurarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarImagemActionPerformed(evt);
            }
        });
        getContentPane().add(btnProcurarImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, -1, 40));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setText("Gerenciar Obras");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        btnExcluir.setText("Excluir");
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 110, 30));

        tb_dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_dados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 1050, 260));

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 710, 110, 30));

        try {
            txtDataObra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtDataObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 79, 200, 30));

        rdbObraFisica.setText("Obra Física");
        rdbObraFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbObraFisicaActionPerformed(evt);
            }
        });
        getContentPane().add(rdbObraFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, -1, -1));

        rdbObraVirtual.setText("Obra Virtual");
        getContentPane().add(rdbObraVirtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtDadosBiograficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDadosBiograficosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDadosBiograficosActionPerformed

    private void txtDoadorObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoadorObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoadorObraActionPerformed

    private void btnProcurarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarImagemActionPerformed
        String caminho = " ";
        JFileChooser jchooser = new JFileChooser();
        jchooser.showOpenDialog(null);
        File f = jchooser.getCurrentDirectory();
        //String filename = getAbsolutePath();
       // path.setText(f);
    }//GEN-LAST:event_btnProcurarImagemActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        Obra obra = new Obra();
        //SimpleDateFormat format = new SimpleDateFormat("yyyy/MM/dd");


        obra.setAutor(txtAutor.getText());
        obra.setDadosBiograficos(txtDadosBiograficos.getText());
        obra.setTitulo(txtTitulo.getText());
        obra.setCategoria(cmbTipoObra.getSelectedItem().toString());

        String xgh = txtDataObra.getText();
        String[] parts = xgh.split("/");
        String part1 = parts[0];
        String part2 = parts[1];
        String part3 = parts[2];

        int day = Integer.parseInt(part1);
        int month = Integer.parseInt(part2) - 1;
        int year = Integer.parseInt(part3);

        obra.setDataDeObra(new GregorianCalendar(year,month,day));




        /*
        try {
            obra.setDataDeObra(format.parse(txtDataObra.getText()));
        } catch (ParseException ex) {

            Logger.getLogger(FormGerenciaObra.class.getName()).log(Level.SEVERE, null, ex);
        }
        */

        obra.setCategoria(txtCategoria.getText());
        obra.setDoadorDeObra(txtDoadorObra.getText());

        if(rdbObraFisica.isSelected())
            obra.setTipoDeObra("Fisico");
        else
            obra.setTipoDeObra("Virtual");

        controle.registrarObra(obra);


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void rdbObraFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbObraFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbObraFisicaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        DefaultTableModel tableModel = new DefaultTableModel(controle.carregaLinhas(), controle.carregaColuna());
        tb_dados.setModel(tableModel);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.fatec.museu.util.GradientButton btnAlterar;
    private com.fatec.museu.util.GradientButton btnCadastrar;
    private com.fatec.museu.util.GradientButton btnExcluir;
    private com.fatec.museu.util.GradientButton btnProcurarImagem;
    private com.fatec.museu.util.GradientButton btnVoltar;
    private javax.swing.ButtonGroup btngTipoObra;
    private javax.swing.JComboBox<String> cmbTipoObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTable tb_dados;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JRadioButton rdbObraFisica;
    private javax.swing.JRadioButton rdbObraVirtual;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtDadosBiograficos;
    private javax.swing.JFormattedTextField txtDataObra;
    private javax.swing.JTextField txtDoadorObra;
    private javax.swing.JTextField txtTitulo;

    // End of variables declaration//GEN-END:variables
}
